[package]
name = "commit-poker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-rational = "0.4.1"
num-integer = "0.1.45"
num-bigint = "0.4.3"
num-traits = "0.2.15"
colored = "2.0.0"
rand = "0.8.5"
